/** Splash background (see ui/loading-bg.png), loaded in BootScene. */
export const UI_LOADING_BG_TEXTURE_KEY = 'ui_loading_bg';
/** Loading progress bar track (see ui/loading-empty.png). */
export const UI_LOADING_BAR_EMPTY_TEXTURE_KEY = 'ui_loading_bar_empty';
/** Loading progress bar fill (see ui/loading-percent.png). */
export const UI_LOADING_BAR_FILL_TEXTURE_KEY = 'ui_loading_bar_fill';

/** Stable texture key for shop detail stat line backgrounds (see ui/text-background.png). */
export const UI_TEXT_BACKGROUND_TEXTURE_KEY = 'ui_text_background';

/** Build placement confirm (see ui/check-icon.png). */
export const UI_BUILD_CHECK_TEXTURE_KEY = 'ui_build_check';
/** Build placement cancel (see ui/cancel-icon.png). */
export const UI_BUILD_CANCEL_TEXTURE_KEY = 'ui_build_cancel';
/** Build placement rotate (see ui/turn.png). */
export const UI_BUILD_TURN_TEXTURE_KEY = 'ui_build_turn';
/** Object edit move (see ui/movement-icon.png). */
export const UI_OBJECT_MOVE_TEXTURE_KEY = 'ui_object_move';
/** Object edit upgrade (see ui/upgrade.png). */
export const UI_OBJECT_UPGRADE_TEXTURE_KEY = 'ui_object_upgrade';
/** Object edit feed (see ui/feed.png). */
export const UI_OBJECT_FEED_TEXTURE_KEY = 'ui_object_feed';
/** Object edit remove (see ui/remove.png). */
export const UI_OBJECT_REMOVE_TEXTURE_KEY = 'ui_object_remove';
/** Livestock sell action (see ui/sell.png). */
export const UI_OBJECT_SELL_TEXTURE_KEY = 'ui_object_sell';
/** Walk-to destination marker (see ui/coming.png). */
export const UI_COMING_TEXTURE_KEY = 'ui_coming';
/** Livestock hungry warning indicator (see animals/warning.png). */
export const LIVESTOCK_WARNING_TEXTURE_KEY = 'livestock_warning';
/** Non-uniform warning icon scale: keep height, squash width. */
export const LIVESTOCK_WARNING_WIDTH_SCALE = 0.5;

/** Asset manifest: key -> relative path under src/assets */
export interface AssetEntry {
  key: string;
  path: string;
  placeholderColor: number;
  width?: number;
  height?: number;
}

export const ASSET_MANIFEST: AssetEntry[] = [
  { key: 'grass', path: 'tiles/grass.png', placeholderColor: 0x5cb85c, width: 64, height: 32 },
  { key: 'grass_light', path: 'tiles/grass_light.png', placeholderColor: 0x7dce7d, width: 64, height: 32 },
  { key: 'flower_ground', path: 'tiles/flower_ground.png', placeholderColor: 0x9b59b6, width: 64, height: 32 },
  { key: 'soil', path: 'tiles/soil.png', placeholderColor: 0x8b6914, width: 64, height: 32 },
  { key: 'mud', path: 'tiles/mud.png', placeholderColor: 0x6d4c41, width: 64, height: 32 },
  { key: 'empty_plot', path: 'tiles/empty_plot.png', placeholderColor: 0x6d4c2e, width: 64, height: 32 },
  { key: 'wet_soil', path: 'tiles/wet_soil.png', placeholderColor: 0x5d4037, width: 64, height: 32 },
  { key: 'farm_plot', path: 'tiles/farm_plot.png', placeholderColor: 0x7a5c1e, width: 64, height: 32 },
  { key: 'field_border', path: 'tiles/field_border.png', placeholderColor: 0x6b8e23, width: 64, height: 32 },
  { key: 'stone_path', path: 'tiles/stone_path.png', placeholderColor: 0x9e9e9e, width: 64, height: 32 },
  { key: 'path', path: 'tiles/path.png', placeholderColor: 0x8d6e63, width: 64, height: 32 },
  { key: 'road_corner', path: 'tiles/road_corner.png', placeholderColor: 0x757575, width: 64, height: 32 },
  { key: 'bridge_tile', path: 'tiles/bridge_tile.png', placeholderColor: 0x795548, width: 64, height: 32 },
  { key: 'water', path: 'tiles/water.png', placeholderColor: 0x3498db, width: 64, height: 32 },
  {
    key: 'water_1_border_top-left',
    path: 'tiles/water_1_border_top-left.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_1_border_top-right',
    path: 'tiles/water_1_border_top-right.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_1_border_bottom-left',
    path: 'tiles/water_1_border_bottom-left.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_1_border_bottom-right',
    path: 'tiles/water_1_border_bottom-right.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_2_borders_top',
    path: 'tiles/water_2_borders_top.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_2_borders_left',
    path: 'tiles/water_2_borders_left.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_2_borders_right',
    path: 'tiles/water_2_borders_right.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_2_borders_bottom',
    path: 'tiles/water_2_borders_bottom.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_2_borders_face_to_face_left',
    path: 'tiles/water_2_borders_face_to_face_left.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_2_borders_face_to_face_right',
    path: 'tiles/water_2_borders_face_to_face_right.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_3_border_left_top',
    path: 'tiles/water_3_border_left_top.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_3_border_left_bottom',
    path: 'tiles/water_3_border_left_bottom.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_3_border_right_bottom',
    path: 'tiles/water_3_border_right_bottom.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  {
    key: 'water_3_border_right_top',
    path: 'tiles/water_3_border_right_top-1.png',
    placeholderColor: 0x3498db,
    width: 64,
    height: 32,
  },
  { key: 'tree_01', path: 'nature/tree_01.png', placeholderColor: 0x2d6a4f, width: 48, height: 64 },
  { key: 'tree_02', path: 'nature/tree_02.png', placeholderColor: 0x40916c, width: 48, height: 64 },
  { key: 'tree_03', path: 'nature/tree_03.png', placeholderColor: 0x52b788, width: 48, height: 64 },
  { key: 'rock_01', path: 'nature/rock_01.png', placeholderColor: 0x7f8c8d, width: 40, height: 32 },
  { key: 'bush_01', path: 'nature/bush_01.png', placeholderColor: 0x52b788, width: 36, height: 28 },
  { key: 'house_lv1', path: 'buildings/house_lv1.png', placeholderColor: 0xe76f51, width: 80, height: 72 },
  { key: 'house_lv2', path: 'buildings/house_lv2.png', placeholderColor: 0xd62828, width: 88, height: 80 },
  { key: 'barn_lv1', path: 'buildings/barn_lv1.png', placeholderColor: 0xc1121f, width: 88, height: 64 },
  { key: 'barn_lv2', path: 'buildings/barn_lv2.png', placeholderColor: 0x9d0208, width: 96, height: 72 },
  { key: 'silo_lv1', path: 'buildings/silo_lv1.png', placeholderColor: 0xadb5bd, width: 48, height: 80 },
  { key: 'coop_lv1', path: 'buildings/coop_lv1.png', placeholderColor: 0xf4a261, width: 72, height: 56 },
  { key: 'chicken_house', path: 'animals/chicken_house.png', placeholderColor: 0xf4a261, width: 112, height: 96 },
  { key: 'cow_house', path: 'animals/cow_house.png', placeholderColor: 0x8d6e63, width: 112, height: 96 },
  { key: 'duck_house', path: 'animals/duck_house.png', placeholderColor: 0xffcc80, width: 112, height: 96 },
  { key: 'fish_house', path: 'animals/fish_house.png', placeholderColor: 0x4fc3f7, width: 112, height: 96 },
  { key: 'pig_house', path: 'animals/pig_house.png', placeholderColor: 0xf8bbd0, width: 112, height: 96 },
  { key: 'sheep_house', path: 'animals/sheep_house.png', placeholderColor: 0xe0e0e0, width: 112, height: 96 },
  { key: 'goat_house', path: 'animals/goat_house.png', placeholderColor: 0xd7ccc8, width: 112, height: 96 },
  { key: 'chicken_child', path: 'animals/chicken_child.png', placeholderColor: 0xffe082, width: 48, height: 40 },
  { key: 'chicken_ault', path: 'animals/chicken_adult.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'chicken_ault_1', path: 'animals/chicken_adult_1.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'chicken_ault_2', path: 'animals/chicken_adult_2.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'chicken_ault_3', path: 'animals/chicken_adult_3.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'cow_child', path: 'animals/cow_child.png', placeholderColor: 0xbcaaa4, width: 52, height: 44 },
  { key: 'cow_ault', path: 'animals/cow_adult.png', placeholderColor: 0x8d6e63, width: 56, height: 48 },
  { key: 'cow_ault_2', path: 'animals/cow_adult_2.png', placeholderColor: 0x8d6e63, width: 56, height: 48 },
  { key: 'duck_child', path: 'animals/duck_child.png', placeholderColor: 0xffe0b2, width: 44, height: 38 },
  { key: 'duck_ault_1', path: 'animals/duck_adult_1.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'duck_ault_2', path: 'animals/duck_adult_2.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'duck_ault_3', path: 'animals/duck_adult_3.png', placeholderColor: 0xffcc80, width: 48, height: 40 },
  { key: 'pig_child', path: 'animals/pig_child.png', placeholderColor: 0xf8bbd0, width: 44, height: 38 },
  { key: 'pig_child_1', path: 'animals/pig_child_1.png', placeholderColor: 0xf8bbd0, width: 44, height: 38 },
  { key: 'pig_adult', path: 'animals/pig_adult.png', placeholderColor: 0xf06292, width: 52, height: 46 },
  { key: 'pig_adult_1', path: 'animals/pig_adult_1.png', placeholderColor: 0xf06292, width: 52, height: 46 },
  { key: 'fish_1', path: 'animals/fish_adult.png', placeholderColor: 0x4fc3f7, width: 40, height: 32 },
  { key: 'fish_2', path: 'animals/fish_adult_1.png', placeholderColor: 0x4fc3f7, width: 40, height: 32 },
  { key: 'fish_3', path: 'animals/fish_adult_2.png', placeholderColor: 0x4fc3f7, width: 40, height: 32 },
  { key: 'fish_4', path: 'animals/fish_adult_3.png', placeholderColor: 0x4fc3f7, width: 40, height: 32 },
  { key: 'fish_child', path: 'animals/fish_child.png', placeholderColor: 0x4fc3f7, width: 40, height: 32 },
  { key: 'sheep_child', path: 'animals/sheep_child.png', placeholderColor: 0xe0e0e0, width: 48, height: 40 },
  { key: 'sheep_ault', path: 'animals/sheep_adult.png', placeholderColor: 0xe0e0e0, width: 52, height: 44 },
  { key: 'sheep_ault_1', path: 'animals/sheep_adult_1.png', placeholderColor: 0xe0e0e0, width: 52, height: 44 },
  { key: 'sheep_ault_2', path: 'animals/sheep_adult_2.png', placeholderColor: 0xe0e0e0, width: 52, height: 44 },
  { key: 'goat_child', path: 'animals/goat_child.png', placeholderColor: 0xd7ccc8, width: 48, height: 40 },
  { key: 'goat_ault', path: 'animals/goat_adult.png', placeholderColor: 0xbcaaa4, width: 52, height: 44 },
  { key: 'goat_ault_1', path: 'animals/goat_adult_1.png', placeholderColor: 0xbcaaa4, width: 52, height: 44 },
  { key: 'goat_ault_2', path: 'animals/goat_adult_2.png', placeholderColor: 0xbcaaa4, width: 52, height: 44 },
  { key: 'wheat_stage1', path: 'crops/wheat_stage1.png', placeholderColor: 0xc9a227, width: 32, height: 24 },
  { key: 'wheat_stage2', path: 'crops/wheat_stage2.png', placeholderColor: 0xd4af37, width: 32, height: 32 },
  { key: 'wheat_stage3', path: 'crops/wheat_stage3.png', placeholderColor: 0xe6c229, width: 36, height: 36 },
  { key: 'wheat_stage4', path: 'crops/wheat_stage4.png', placeholderColor: 0xf1c40f, width: 36, height: 40 },
  { key: 'wheat', path: 'stores/wheat.png', placeholderColor: 0xf1c40f, width: 32, height: 32 },
  { key: 'item_corn', path: 'stores/corn.png', placeholderColor: 0xffeb3b, width: 32, height: 32 },
  { key: 'item_carrot', path: 'stores/carrot.png', placeholderColor: 0xe67e22, width: 32, height: 32 },
  { key: 'item_pumpkin', path: 'stores/pumpkin.png', placeholderColor: 0xff5722, width: 32, height: 32 },
  { key: 'item_tomato', path: 'stores/tomato.png', placeholderColor: 0xe74c3c, width: 32, height: 32 },
  { key: 'bread', path: 'stores/bread.png', placeholderColor: 0xdeb887, width: 32, height: 32 },
  { key: 'cake', path: 'stores/cake.png', placeholderColor: 0xffb6c1, width: 32, height: 32 },
  { key: 'candy', path: 'stores/candy.png', placeholderColor: 0xff69b4, width: 32, height: 32 },
  { key: 'cookie', path: 'stores/cookie.png', placeholderColor: 0xd2691e, width: 32, height: 32 },
  { key: 'juice', path: 'stores/juice.png', placeholderColor: 0xffa500, width: 32, height: 32 },
  { key: 'milk', path: 'stores/milk.png', placeholderColor: 0xfffafa, width: 32, height: 32 },
  { key: 'flour', path: 'stores/flour.png', placeholderColor: 0xf5f5dc, width: 32, height: 32 },
  { key: 'corn_stage1', path: 'crops/corn_stage1.png', placeholderColor: 0x7cb342, width: 28, height: 20 },
  { key: 'corn_stage2', path: 'crops/corn_stage2.png', placeholderColor: 0x8bc34a, width: 32, height: 36 },
  { key: 'corn_stage3', path: 'crops/corn_stage3.png', placeholderColor: 0xaed581, width: 36, height: 42 },
  { key: 'corn_stage4', path: 'crops/corn_stage4.png', placeholderColor: 0xffeb3b, width: 36, height: 48 },
  { key: 'carrot_stage1', path: 'crops/carrot_stage1.png', placeholderColor: 0xe67e22, width: 28, height: 20 },
  { key: 'carrot_stage2', path: 'crops/carrot_stage2.png', placeholderColor: 0xf39c12, width: 32, height: 28 },
  { key: 'carrot_stage3', path: 'crops/carrot_stage3.png', placeholderColor: 0xe74c3c, width: 34, height: 34 },
  { key: 'carrot_stage4', path: 'crops/carrot_stage4.png', placeholderColor: 0xd35400, width: 36, height: 40 },
  { key: 'pumpkin_stage1', path: 'crops/pumpkin_stage1.png', placeholderColor: 0x7cb342, width: 28, height: 20 },
  { key: 'pumpkin_stage2', path: 'crops/pumpkin_stage2.png', placeholderColor: 0x8bc34a, width: 32, height: 30 },
  { key: 'pumpkin_stage3', path: 'crops/pumpkin_stage3.png', placeholderColor: 0xff9800, width: 38, height: 36 },
  { key: 'pumpkin_stage4', path: 'crops/pumpkin_stage4.png', placeholderColor: 0xff5722, width: 42, height: 44 },
  { key: 'tomato_stage1', path: 'crops/tomato_stage1.png', placeholderColor: 0x7cb342, width: 28, height: 20 },
  { key: 'tomato_stage2', path: 'crops/tomato_stage2.png', placeholderColor: 0xe74c3c, width: 32, height: 28 },
  { key: 'tomato_stage3', path: 'crops/tomato_stage3.png', placeholderColor: 0xc0392b, width: 34, height: 34 },
  { key: 'tomato_stage4', path: 'crops/tomato_stage4.png', placeholderColor: 0xe74c3c, width: 36, height: 40 },
  { key: 'farmer_digging', path: 'characters/digging.png', placeholderColor: 0x8d6e63, width: 32, height: 48 },
  { key: 'farmer_watering', path: 'characters/watering.png', placeholderColor: 0x3498db, width: 32, height: 48 },
  { key: 'farmer_harvesting', path: 'characters/harvesting.png', placeholderColor: 0xf39c12, width: 32, height: 48 },
  { key: 'watering_can', path: 'ui/watering_can.png', placeholderColor: 0x3498db, width: 28, height: 28 },
  { key: 'farmer_idle_front', path: 'characters/farmer_idle_front.png', placeholderColor: 0x3498db, width: 32, height: 48 },
  { key: 'farmer_idle_back', path: 'characters/farmer_idle_back.png', placeholderColor: 0x3498db, width: 32, height: 48 },
  { key: 'farmer_idle_left', path: 'characters/farmer_idle_left.png', placeholderColor: 0x3498db, width: 32, height: 48 },
  { key: 'farmer_idle_right', path: 'characters/farmer_idle_right.png', placeholderColor: 0x3498db, width: 32, height: 48 },
  { key: 'farmer_walk_front_1', path: 'characters/farmer_walk_front_1.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_front_2', path: 'characters/farmer_walk_front_2.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_left_1', path: 'characters/farmer_walk_left_1.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_left_2', path: 'characters/farmer_walk_left_2.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_right_1', path: 'characters/farmer_walk_right_1.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_right_2', path: 'characters/farmer_walk_right_2.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_back_1', path: 'characters/farmer_walk_back_1.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  { key: 'farmer_walk_back_2', path: 'characters/farmer_walk_back_2.png', placeholderColor: 0x2980b9, width: 32, height: 48 },
  {
    key: 'ui_background',
    path: 'ui/background.png',
    placeholderColor: 0x2d4a2a,
    width: 1492,
    height: 1054,
  },
  {
    key: 'farm_island',
    path: 'ui/island.png',
    placeholderColor: 0x8b6914,
    width: 1254,
    height: 1254,
  },
  { key: 'coin', path: 'ui/coin.png', placeholderColor: 0xf1c40f, width: 24, height: 24 },
  { key: 'energy', path: 'ui/energy.png', placeholderColor: 0xf1c40f, width: 24, height: 24 },
  { key: 'gem', path: 'ui/gem.png', placeholderColor: 0x9b59b6, width: 24, height: 24 },
  { key: 'seed', path: 'ui/seed.png', placeholderColor: 0x8d6e63, width: 28, height: 28 },
  { key: 'ui_wood', path: 'ui/wood.png', placeholderColor: 0x8d6e63, width: 128, height: 128 },
  { key: 'seed_wheat', path: 'seeds/wheat_seed.png', placeholderColor: 0xc9a227, width: 32, height: 32 },
  { key: 'seed_corn', path: 'seeds/corn_seed.png', placeholderColor: 0xffeb3b, width: 32, height: 32 },
  { key: 'seed_carrot', path: 'seeds/carrot_seed.png', placeholderColor: 0xe67e22, width: 32, height: 32 },
  { key: 'seed_pumpkin', path: 'seeds/pumpkin_seed.png', placeholderColor: 0xff5722, width: 32, height: 32 },
  { key: 'seed_tomato', path: 'seeds/tomato_seed.png', placeholderColor: 0xe74c3c, width: 32, height: 32 },
  { key: 'shovel', path: 'ui/shovel.png', placeholderColor: 0x95a5a6, width: 28, height: 28 },
  { key: 'inventory', path: 'ui/inventory.png', placeholderColor: 0xecf0f1, width: 32, height: 32 },
  { key: 'build', path: 'ui/build.png', placeholderColor: 0xecf0f1, width: 32, height: 32 },
  { key: 'shop', path: 'ui/shop.png', placeholderColor: 0xecf0f1, width: 32, height: 32 },
  { key: 'ui_warehouse', path: 'ui/warehouse.png', placeholderColor: 0x5d4037, width: 1536, height: 1024 },
  { key: 'ui_shop_modal', path: 'ui/shop-modal.png', placeholderColor: 0x5d4037, width: 1399, height: 782 },
  { key: 'ui_tool_modal', path: 'ui/tool-modal.png', placeholderColor: 0x5d4037, width: 1370, height: 686 },
  { key: 'ui_wood_bar', path: 'ui/wood-bar.png', placeholderColor: 0x8d6e63, width: 302, height: 50 },
  {
    key: UI_TEXT_BACKGROUND_TEXTURE_KEY,
    path: 'ui/text-background.png',
    placeholderColor: 0xc4a574,
    width: 194,
    height: 21,
  },
  { key: 'ui_box', path: 'ui/box.png', placeholderColor: 0xc4a574, width: 311, height: 148 },
  { key: 'ui_coin_box', path: 'ui/coin-box.png', placeholderColor: 0xc4a574, width: 168, height: 56 },
  { key: 'ui_diamond_box', path: 'ui/diamond-box.png', placeholderColor: 0xb8a0d4, width: 168, height: 56 },
  { key: 'ui_energy_box', path: 'ui/energy-box.png', placeholderColor: 0xa8c878, width: 168, height: 56 },
  {
    key: 'ui_warehouse_item',
    path: 'ui/warehouse-item.png',
    placeholderColor: 0xc4a574,
    width: 128,
    height: 120,
  },
  {
    key: 'ui_warehouse_items_list_bg',
    path: 'ui/warehouse-items-list-bg.png',
    placeholderColor: 0xe8dcc8,
    width: 77,
    height: 43,
  },
  {
    key: 'ui_warehouse_tablist_bg',
    path: 'ui/warehouse-tablist-bg.png',
    placeholderColor: 0x8d6e63,
    width: 138,
    height: 70,
  },
  {
    key: 'ui_warehouse_process_bg',
    path: 'ui/warehouse-process-bg.png',
    placeholderColor: 0x8d6e63,
    width: 124,
    height: 70,
  },
  {
    key: 'ui_shop_item',
    path: 'ui/shop-item.png',
    placeholderColor: 0xc4a574,
    width: 166,
    height: 157,
  },
  { key: 'ui_tab_all', path: 'ui/all.png', placeholderColor: 0x8d6e63, width: 266, height: 136 },
  { key: 'ui_tab_all_active', path: 'ui/all_active.png', placeholderColor: 0xd4a574, width: 268, height: 138 },
  { key: 'ui_tab_resources', path: 'ui/resources.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  {
    key: 'ui_tab_resources_active',
    path: 'ui/resources_active.png',
    placeholderColor: 0xd4a574,
    width: 260,
    height: 136,
  },
  { key: 'ui_tab_seeds', path: 'ui/seeds.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  { key: 'ui_tab_seeds_active', path: 'ui/seeds_active.png', placeholderColor: 0xd4a574, width: 260, height: 136 },
  { key: 'ui_tab_food', path: 'ui/food.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  { key: 'ui_tab_food_active', path: 'ui/food_active.png', placeholderColor: 0xd4a574, width: 260, height: 136 },
  { key: 'ui_tab_materials', path: 'ui/materials.png', placeholderColor: 0x8d6e63, width: 263, height: 136 },
  { key: 'ui_shop_tab_seeds', path: 'ui/seeds-tab.png', placeholderColor: 0x8d6e63, width: 165, height: 89 },
  { key: 'ui_shop_tab_tools', path: 'ui/tools-tab.png', placeholderColor: 0x8d6e63, width: 165, height: 89 },
  { key: 'ui_shop_tab_farming', path: 'ui/farming-tab.png', placeholderColor: 0x8d6e63, width: 165, height: 89 },
  { key: 'ui_shop_tab_locked', path: 'ui/locked-tab.png', placeholderColor: 0x8d6e63, width: 165, height: 89 },
  { key: 'ui_shop_tab_gear', path: 'ui/gear-tab.png', placeholderColor: 0x8d6e63, width: 165, height: 89 },
  { key: 'ui_shop_tab_storage', path: 'ui/storage-tab.png', placeholderColor: 0x8d6e63, width: 165, height: 89 },
  { key: 'shop_tab_all', path: 'stores/all.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  { key: 'shop_tab_all_active', path: 'stores/all_active.png', placeholderColor: 0xd4a574, width: 268, height: 138 },
  { key: 'shop_tab_seeds', path: 'stores/seeds.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  { key: 'shop_tab_seeds_active', path: 'stores/seeds_active.png', placeholderColor: 0xd4a574, width: 260, height: 136 },
  { key: 'shop_tab_animals', path: 'stores/animals.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  { key: 'shop_tab_animals_active', path: 'stores/animals_active.png', placeholderColor: 0xd4a574, width: 260, height: 136 },
  { key: 'shop_tab_decorations', path: 'stores/decorations.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  {
    key: 'shop_tab_decorations_active',
    path: 'stores/decorations_active.png',
    placeholderColor: 0xd4a574,
    width: 260,
    height: 136,
  },
  { key: 'shop_tab_foods', path: 'stores/foods.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  { key: 'shop_tab_foods_active', path: 'stores/foods_active.png', placeholderColor: 0xd4a574, width: 260, height: 136 },
  { key: 'shop_tab_resources', path: 'stores/resources.png', placeholderColor: 0x8d6e63, width: 260, height: 136 },
  {
    key: 'shop_tab_resources_active',
    path: 'stores/resources_active.png',
    placeholderColor: 0xd4a574,
    width: 260,
    height: 136,
  },
  { key: 'ui_check', path: 'ui/check.png', placeholderColor: 0x27ae60, width: 48, height: 48 },
  {
    key: UI_BUILD_CHECK_TEXTURE_KEY,
    path: 'ui/check-icon.png',
    placeholderColor: 0x27ae60,
    width: 48,
    height: 48,
  },
  {
    key: UI_BUILD_CANCEL_TEXTURE_KEY,
    path: 'ui/cancel-icon.png',
    placeholderColor: 0xc0392b,
    width: 48,
    height: 48,
  },
  {
    key: UI_BUILD_TURN_TEXTURE_KEY,
    path: 'ui/turn.png',
    placeholderColor: 0x5dade2,
    width: 48,
    height: 48,
  },
  {
    key: UI_OBJECT_MOVE_TEXTURE_KEY,
    path: 'ui/movement-icon.png',
    placeholderColor: 0x4a90d9,
    width: 48,
    height: 48,
  },
  {
    key: UI_OBJECT_UPGRADE_TEXTURE_KEY,
    path: 'ui/upgrade.png',
    placeholderColor: 0xe0b04a,
    width: 48,
    height: 48,
  },
  {
    key: UI_OBJECT_FEED_TEXTURE_KEY,
    path: 'ui/feed.png',
    placeholderColor: 0x6fbf73,
    width: 48,
    height: 48,
  },
  {
    key: UI_OBJECT_REMOVE_TEXTURE_KEY,
    path: 'ui/remove.png',
    placeholderColor: 0xc0392b,
    width: 48,
    height: 48,
  },
  {
    key: UI_OBJECT_SELL_TEXTURE_KEY,
    path: 'ui/sell.png',
    placeholderColor: 0xe67e22,
    width: 48,
    height: 48,
  },
  {
    key: LIVESTOCK_WARNING_TEXTURE_KEY,
    path: 'animals/warning.png',
    placeholderColor: 0xff6b6b,
    width: 40,
    height: 40,
  },
  {
    key: 'ui_tab_materials_active',
    path: 'ui/materials_active.png',
    placeholderColor: 0xd4a574,
    width: 263,
    height: 136,
  },
  {
    key: 'ui_process_empty',
    path: 'ui/process_empty.png',
    placeholderColor: 0xc4a574,
    width: 668,
    height: 134,
  },
  {
    key: 'ui_process_fill',
    path: 'ui/process_percent.png',
    placeholderColor: 0x27ae60,
    width: 398,
    height: 82,
  },
  { key: 'harvest', path: 'ui/harvest.png', placeholderColor: 0xf39c12, width: 32, height: 32 },
  {
    key: UI_COMING_TEXTURE_KEY,
    path: 'ui/coming.png',
    placeholderColor: 0x27ae60,
    width: 48,
    height: 48,
  },
  { key: 'ui_button', path: 'ui/button.png', placeholderColor: 0xe76f51, width: 150, height: 78 },
  {
    key: 'ui_plus_devide',
    path: 'ui/plus-devide.png',
    placeholderColor: 0xc4a574,
    width: 348,
    height: 80,
  },
];

export const PLACEHOLDER_KEYS = new Set(ASSET_MANIFEST.map((a) => a.key));

/** Building texture by type and level (1–3) */
export function buildingTextureKey(type: string, level: number): string {
  const lv = Math.min(3, Math.max(1, level));
  if (type === 'house') return lv >= 2 ? 'house_lv2' : 'house_lv1';
  if (type === 'barn') return lv >= 2 ? 'barn_lv2' : 'barn_lv1';
  return 'tree_01';
}
